### PR TITLE
Map zooming and panning

### PR DESCRIPTION
**Pull request by NukieGIT**
I really enjoy playing as artillery in MTC and using your calculator for the funsies, but I sometimes struggle to properly set up the position markers (especially the one responsible for my vehicle's position) and in turn I have to resort to using browser's zoom functionality which is quite cumbersome/clunky. So I decided to enhance the map component by wrapping it in a container I made that supports semi-customizable zooming and panning features.

On a side note, I tried adding controls info required to pan, zoom and reset the map alongside the existing controls tips but to no avail because the entire UI's container would fill the whole window. And honestly I don't know the reason behind this.

image
Instead of:
image

Another issue I've encountered is related to a border; to be exact, using it right here on the `Box` component:
https://github.com/ari-party/mtc-artillery/blob/d54cb285a753cfc112e4dadef21f43ab9022eccc/src/components/molecules/canvas/Container.tsx#L32-L36

Whenever I tried setting a border on it, it would result in a "Maximum update depth exceeded" error. I tried fixing it but in the end I didn't manage do it. What I did understand though, is that it's definitely affected by the `useEffect` hook.

(This is my first ever open-source contribution and I'm aware that I may have made some mistakes, particularly because I've never worked with Next.js and have limited experience with barebones React. So please point out any issues, and I'll try my best to address them.)

### CODE REVIEW

**Comment by ari-party** [comment]
I'm unable to control the map with scroll wheel?

Also with the container filling up the screen, it's not constrained, it can be any size it wants as long it's on a 1:1 aspect ratio.

**Comment by ari-party** [comment]
Pressing and holding the middle mouse button in the container, then moving the mouse out of the container and releasing it, makes it think middle mouse button is still being held.
chrome_SAB42W7OG1

**Comment by NukieGIT** [comment]
I completely overlooked that 😅, my bad. I'll get to fixing this ASAP.

**Comment by NukieGIT** [comment]
I've fixed the issue, but now it got me thinking; should I make it so the map still can be moved when the mouse is outside of the container? Although at first glance it seems like I might have to play with a couple of more document mouse event listeners in order to do that, ~~since I'm pretty sure it's impossible to detect middle click with pointer events...~~. After some reading, I realized you can.

**Comment by ari-party** [comment]
Are you able to make it use LMB for dragging instead? Just like in game?

**Comment by NukieGIT** [comment]
I am, however I'm not sure if I'll be to do it today.

**Comment by NukieGIT** [comment]
Alright, I got it working, hope everything's good.

**Comment by ari-party** [comment]
Currently looking into [react-zoom-pan-pinch](https://github.com/BetterTyped/react-zoom-pan-pinch/) for possibly better support.

**Pull request merged**
